import React from "react";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { Text, ScrollView, StatusBar } from "native-base";
import { design } from "../estilos/temas";

const Tab = createBottomTabNavigator();

export default function Comprar() {
  return (
      <ScrollView flex={1} backgroundColor='gray.700'>
        <StatusBar backgroundColor={design.colors.gray[700]}/>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
        <Text>Comprar</Text>
      </ScrollView>
  );
}